server:
  port: 8181
  servlet:
    context-path: /elastic-query-service

elastic-query-service:
  version: v1

elastic-config:
  index-name: twitter-index
  connection-url: http://localhost:9200
  connect-timeout-ms: 5000
  socket-timeout-ms: 30000
  is-repository: true

user-config:
  username: test
  password: test1234
  roles: USER

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html

security:
  paths-to-ignore: /api-docs
